# from galaxy
#- src: jijisa.crio
#  name: iorchard.crio
#
# from github
- src: https://github.com/iorchard/iorchard.crio
  version: main
- src: https://github.com/iorchard/iorchard.k8s
  version: main
- src: https://github.com/iorchard/iorchard.cilium
  version: main
