---
# global
ansible_ssh_pass: "{{ vault_ssh_pass }}"
ansible_become_pass: "{{ vault_sudo_pass }}"
ansible_python_interpreter: "/usr/bin/python3"

# keepalived
keepalived_interface: "eth0"
keepalived_vip: "192.168.21.120"

# haproxy
haproxy_bind_port: "8443"

# crio
crio_version: "1.21"

# k8s
kubernetes_version: "v1.21.0"

# cilium
cilium_version: "1.9.6"
cilium_pod_cidr: "10.0.0.0/8"
cilium_pod_mask: 24
cilium_lb_mode: "dsr"
cilium_lb_algorithm: "maglev"
...
