---
# global
ansible_ssh_pass: "{{ vault_ssh_pass }}"
ansible_become_pass: "{{ vault_sudo_pass }}"
ansible_python_interpreter: "/usr/bin/python3"

# keepalived
keepalived_vip: "192.168.21.120"

# crio
crio_version: "1.20"

# k8s
control_plance_endpoint_ip: "{{ keepalived_vip }}"
kubernetes_version: "v1.21.0"
cilium_version: "1.9.6"
...
