---
# global
ansible_ssh_pass: "{{ vault_ssh_pass }}"
ansible_become_pass: "{{ vault_sudo_pass }}"
ansible_python_interpreter: "/usr/bin/python3"

# keepalived
keepalived_vip: "192.168.21.120"

# crio
crio_version: "1.20"

# k8s
control_plane_endpoint_ip: "{{ keepalived_vip }}"
kubernetes_version: "v1.21.0"

# cilium
cilium_version: "1.9.6"
cilium_pod_cidr: "10.0.0.0/8"
cilium_pod_mask: 24
cilium_lb_mode: "dsr"
cilium_lb_algorithm: "maglev"
...
